\i seeds/seed.1_brands.sql
\i seeds/seed.1_certifications.sql
\i seeds/seed.1_fabric_types.sql
\i seeds/seed.1_factories.sql
\i seeds/seed.1_fibers_and_material_types.sql
\i seeds/seed.1_notion_types.sql
\i seeds/seed.2_fabrics.sql
\i seeds/seed.2_fibers_and_materials.sql
\i seeds/seed.2_fibers_to_certifications.sql
\i seeds/seed.2_fibers_to_factories.sql
\i seeds/seed.2_filter_options.sql
\i seeds/seed.2_notions.sql
\i seeds/seed.2_products.sql
\i seeds/seed.2_sizes.sql
\i seeds/seed.3_fabrics_to_certifications.sql
\i seeds/seed.3_fabrics_to_factories.sql
\i seeds/seed.3_fabrics_to_fibers_and_materials.sql
\i seeds/seed.3_fabrics_to_products.sql
\i seeds/seed.3_fibers_to_products.sql
\i seeds/seed.3_notions_to_certifications.sql
\i seeds/seed.3_notions_to_fibers_and_materials.sql
\i seeds/seed.3_notions_to_products.sql
\i seeds/seed.3_product_cmts_to_certifications.sql
\i seeds/seed.3_product_cmts_to_factories.sql
\i seeds/seed.3_product_images.sql
\i seeds/seed.3_sizes_to_products.sql