const table = require("heroku-cli-util/lib/table")

exports.up = function(knex) {
    return knex.schema.createTable('product_images', table => {
        table.increments('id').primary()
        table.integer('product_id').unsigned().notNullable()
        table.foreign('product_id').references('id').inTable('products').onDelete('CASCADE')
        table.string('product_image_url').notNullable()
        table.integer('color_id').unsigned().notNullable()
        table.foreign('color_id').references('id').inTable('product_colors').onDelete('CASCADE')
        table.boolean('primary_image_for_color').notNullable()
        table.boolean('approved_by_admin').defaultTo(false)
        table.timestamps(true, true)
    })
}

exports.down = function(knex) {
  return knex.schema.dropTable('product_images')
}

// CREATE TABLE product_images (
//     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//     product_id INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
//     product_image_url TEXT NOT NULL,
//     color_id INTEGER REFERENCES product_colors(id) ON DELETE CASCADE NOT NULL,
//     primary_image_for_color BOOLEAN NOT NULL,
//     approved_by_admin BOOLEAN DEFAULT false,
//     date_published TIMESTAMPTZ DEFAULT now() NOT NULL
// );