exports.up = function(knex) {
  return knex.schema.createTable('fiber_and_material_types', table => {
    table.increments('id').primary()
    table.string('english_name').notNullable()
    table.enu('fiber_type_class', ['protein fiber', 'naturally occuring cellulosic fiber', 'manufactured cellulosic fiber', 'synthetic fiber', 'undetermined']).defaultTo('undetermined')
    table.boolean('approved_by_admin').defaultTo(false)
    table.timestamps(true, true)
  })
  
}

exports.down = function(knex) {
  return knex.schema.dropTable('fiber_and_material_types')
}

// CREATE TYPE fiber_or_material_class AS ENUM (
//     'protein fiber',
//     'naturally occuring cellulosic fiber',
//     'manufactured cellulosic fiber',
//     'synthetic fiber',
//     'undetermined'
// );

// CREATE TABLE fiber_and_material_types (
//     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//     english_name TEXT NOT NULL,
//     fiber_type_class fiber_or_material_class DEFAULT 'undetermined',
//     date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
//     approved_by_admin BOOLEAN DEFAULT false
// );