exports.up = function(knex) {
    return knex.schema.createTable('fabrics', table => {
        table.increments('id').primary()
        table.integer('brand_id').unsigned().notNullable()
        table.foreign('brand_id').references('id').inTable('brands').onDelete('CASCADE')
        table.smallint('fabric_mill_country').defaultTo(1)
        table.smallint('fabric_mill_id').notNullable()
        table.text('fabric_mill_notes').defaultTo('')
        table.smallint('dye_print_finish_country').defaultTo(1)
        table.smallint('dye_print_finish_id').notNullable()
        table.text('dye_print_finish_notes').defaultTo('')
        table.boolean('approved_by_admin').defaultTo(false)
        table.timestamps(true, true)
    })
}

exports.down = function(knex) {
    return knex.schema.dropTable('fabrics')
}

// CREATE TABLE fabrics (
//     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//     brand_id INTEGER REFERENCES brands(id) ON DELETE CASCADE NOT NULL,
//     fabric_mill_country INTEGER DEFAULT 1,
//     fabric_mill_id INTEGER NOT NULL,
//     fabric_mill_notes TEXT,
//     dye_print_finish_country INTEGER DEFAULT 1,
//     dye_print_finish_id INTEGER NOT NULL,
//     dye_print_finish_notes TEXT,
//     approved_by_admin BOOLEAN DEFAULT false,
//     date_published TIMESTAMPTZ DEFAULT now() NOT NULL
// );    