exports.up = function(knex) {
    return knex.schema.createTable('notion_types', table => {
        table.increments('id').primary()
        table.string('english_name').notNullable()
        table.boolean('approved_by_admin').defaultTo(false)
        table.timestamps(true, true)
    })
}

exports.down = function(knex) {
    return knex.schema.dropTable('notion_types')
}

// CREATE TABLE notion_types (
//     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//     english_name TEXT NOT NULL,
//     approved_by_admin BOOLEAN DEFAULT false,
//     date_published TIMESTAMPTZ DEFAULT now() NOT NULL
// );