exports.up = function(knex) {
    return knex.schema.createTable('fibers_and_materials', table => {
        table.increments('id').primary()
        table.integer('fiber_or_material_type_id').unsigned().notNullable()
        table.foreign('fiber_or_material_type_id').references('id').inTable('fiber_and_material_types').onDelete('CASCADE')
        table.integer('brand_id').unsigned().notNullable()
        table.foreign('brand_id').references('id').inTable('brands').onDelete('CASCADE')
        table.smallint('producer_country').defaultTo(1)
        table.integer('producer_id').unsigned().notNullable()
        table.foreign('producer_id').references('id').inTable('factories').onDelete('CASCADE')
        table.text('production_notes').defaultTo('')
        table.boolean('approved_by_admin').defaultTo(false)
        table.timestamps(true, true)
    })
}

exports.down = function(knex) {
    return knex.schema.dropTable('fibers_and_materials')
}

// CREATE TABLE fibers_and_materials (
//     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//     fiber_or_material_type_id INTEGER REFERENCES fiber_and_material_types(id) ON DELETE CASCADE NOT NULL,
//     brand_id INTEGER REFERENCES brands(id) ON DELETE CASCADE NOT NULL,
//     producer_country INTEGER DEFAULT 1,
//     producer_id INTEGER REFERENCES factories(id) ON DELETE CASCADE NOT NULL,
//     production_notes TEXT,
//     approved_by_admin BOOLEAN DEFAULT false,
//     date_published TIMESTAMPTZ DEFAULT now() NOT NULL
// );