CREATE TYPE category_class AS ENUM (
    'clothing',
    'accessories',
    'shoes'                            
);

CREATE TABLE categories (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  english_name TEXT NOT NULL,
  class category_class NOT NULL DEFAULT 'clothing'
);