CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    english_name TEXT NOT NULL,
    brand_id INTEGER REFERENCES brands(id) NOT NULL,
    category_id INTEGER REFERENCES categories(id) NOT NULL,
    product_url TEXT NOT NULL,
    home_currency TEXT NOT NULL,
    cost_in_home_currency MONEY NOT NULL,
    cmt_country TEXT NOT NULL,
    cmt_factory_notes TEXT NOT NULL,
    approved_by_admin BOOLEAN NOT NULL
);