CREATE TYPE fabric_class AS ENUM (
    'knit',
    'woven',
    'non-woven'
);

CREATE TABLE fabric_types (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    english_name TEXT NOT NULL,
    class fabric_class NOT NULL
);