CREATE TABLE brands (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  english_name TEXT NOT NULL,
  website TEXT NOT NULL,
  home_currency INTEGER DEFAULT 1,
  size_system TEXT NOT NULL,
  approved_by_admin BOOLEAN DEFAULT false,
  date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);