CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    english_name TEXT NOT NULL,
    brand_id INTEGER REFERENCES brands(id) ON DELETE CASCADE NOT NULL,
    category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE NOT NULL,
    feature_image_url TEXT NOT NULL,
    multiple_color_options BOOLEAN NOT NULL,
    cost_in_home_currency double precision NOT NULL,
    product_url TEXT NOT NULL,
    wash_id INTEGER REFERENCES wash_instructions(id) ON DELETE CASCADE,
    dry_id INTEGER REFERENCES dry_instructions(id) ON DELETE CASCADE,
    cmt_notes TEXT,
    approved_by_admin BOOLEAN DEFAULT false,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);