CREATE TYPE fiber_or_material_class AS ENUM (
    'protein fiber',
    'naturally occuring cellulosic fiber',
    'manufactured cellulosic fiber',
    'synthetic fiber'
);

CREATE TABLE fiber_and_material_types (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    english_name TEXT NOT NULL,
    class fiber_or_material_class NOT NULL,
    approved_by_admin BOOLEAN NOT NULL DEFAULT false,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);