CREATE TABLE fibers_and_materials (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fiber_or_material_type_id INTEGER REFERENCES fiber_and_material_types(id) ON DELETE CASCADE NOT NULL,
    brand_id INTEGER REFERENCES brands(id) ON DELETE CASCADE NOT NULL,
    producer_country NUMBER,
    producer_id NUMBER REFERENCES factories(id) ON DELETE CASCADE NOT NULL,
    production_notes TEXT,
    approved_by_admin BOOLEAN DEFAULT false,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);