CREATE TYPE fabric_class AS ENUM (
    'knit',
    'woven',
    'non-woven'
);

CREATE TABLE fabric_types (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    english_name TEXT NOT NULL,
    fabric_type_class fabric_class NOT NULL,
    approved_by_admin BOOLEAN DEFAULT false NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);