CREATE TYPE fabric_class AS ENUM (
    'knit',
    'woven',
    'non-woven',
    'undetermined'
);

CREATE TABLE fabric_types (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    english_name TEXT NOT NULL,
    fabric_type_class fabric_class DEFAULT 'undetermined',
    approved_by_admin BOOLEAN DEFAULT false,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);