CREATE TABLE fabrics (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fabric_type_id INTEGER REFERENCES fabric_types(id) ON DELETE CASCADE NOT NULL,
    brand_id INTEGER REFERENCES brands(id) ON DELETE CASCADE NOT NULL,
    fabric_mill_country TEXT,
    fabric_mill_notes TEXT,
    dye_print_finish_country TEXT,
    dye_print_finish_notes TEXT,
    approved_by_admin BOOLEAN DEFAULT false NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);