CREATE TABLE fabrics (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand_id INTEGER REFERENCES brands(id) ON DELETE CASCADE NOT NULL,
    fabric_mill_country INTEGER NOT NULL,
    fabric_mill_id INTEGER NOT NULL,
    fabric_mill_notes TEXT,
    dye_print_finish_country INTEGER NOT NULL,
    dye_print_finish_id INTEGER NOT NULL,
    dye_print_finish_notes TEXT,
    approved_by_admin BOOLEAN DEFAULT false,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);    