CREATE TABLE notions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    notion_type_id INTEGER REFERENCES notion_types(id) ON DELETE CASCADE NOT NULL,
    brand_id INTEGER REFERENCES brands(id) ON DELETE CASCADE NOT NULL,
    notion_factory_country TEXT,
    notion_factory_id INTEGER REFERENCES factories(id) ON DELETE CASCADE NOT NULL,
    notion_factory_notes TEXT,
    approved_by_admin BOOLEAN DEFAULT false,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);