CREATE TABLE notions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    notion_type_id INTEGER REFERENCES notion_types(id) ON DELETE CASCADE NOT NULL,
    brand_id INTEGER REFERENCES brands(id) ON DELETE CASCADE NOT NULL,
    manufacturer_country INTEGER DEFAULT 1,
    manufacturer_id INTEGER REFERENCES factories(id) ON DELETE CASCADE NOT NULL,
    manufacturer_notes TEXT,
    material_type_id INTEGER REFERENCES fiber_and_material_types(id) ON DELETE CASCADE NOT NULL,
    material_origin_id INTEGER DEFAULT 1,
    material_producer_id INTEGER REFERENCES factories(id) ON DELETE CASCADE NOT NULL,
    material_notes TEXT,
    approved_by_admin BOOLEAN DEFAULT false,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);