CREATE TABLE size_types (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    english_name TEXT NOT NULL
);

insert into size_types
(english_name)
values
    ('dress size'),
    ('waist size'),
    ('shoe size'),
    ('bra size'),
    ('hat size'),
    ('belt size');