DROP TABLE IF EXISTS sizes CASCADE;
DROP TYPE IF EXISTS country_systems CASCADE;
DROP TYPE IF EXISTS size_categories CASCADE;
DROP TYPE IF EXISTS size_classes CASCADE;
DROP TYPE IF EXISTS us_sizes CASCADE;