CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    handle TEXT,
    name TEXT,
    website TEXT,
    profile_pic TEXT,
    bio TEXT,
    public BOOLEAN DEFAULT false,
    account_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

insert into users 
(email, password, handle, name, website, profile_pic, bio, public)
values
    (
        'georgia.kirkpatrick@gmail.com', 
        'testpassword', 
        'georgiakirkpatrick', 
        'Georgia Kirkpatrick', 
        'georgiakirkpatrick.com', 
        'https://www.talk-business.co.uk/wp-content/uploads/2016/05/shutterstock_128709044.jpg', 
        'Georgia is a computer programmer from Portland, Oregon.',
        false
    );
