\i seed.1_brands.sql
\i seed.1_certifications.sql
\i seed.1_dry_instructions.sql
\i seed.1_fabric_types.sql
\i seed.1_factories.sql
\i seed.1_fibers_and_material_types.sql
\i seed.1_notion_types.sql
\i seed.1_size_classes.sql
\i seed.1_size_types.sql
\i seed.1_wash_instructions.sql
\i seed.2_categories_to_sp_filters.sql
\i seed.2_fabrics.sql
\i seed.2_fibers_and_materials.sql
\i seed.2_fibers_to_certifications.sql
\i seed.2_fibers_to_factories.sql
\i seed.2_filter_options.sql
\i seed.2_notions.sql
\i seed.2_products.sql
\i seed.2_sizes.sql
\i seed.3_fabrics_to_certifications.sql
\i seed.3_fabrics_to_factories.sql
\i seed.3_fabrics_to_fibers_and_materials.sql
\i seed.3_fabrics_to_products.sql
\i seed.3_fibers_to_products.sql
\i seed.3_notions_to_certifications.sql
\i seed.3_notions_to_fibers_and_materials.sql
\i seed.3_notions_to_products.sql
\i seed.3_product_cmts_to_certifications.sql
\i seed.3_product_cmts_to_factories.sql
\i seed.3_product_images.sql
\i seed.3_size_classes_to_products.sql
\i seed.3_sizes_to_products.sql