insert into filter_options
(english_name, filter_group_id)
values
    ('Dresses', '1'),
    ('Base layer', '1'),
    ('Leggings', '1'),
    ('Pants', '1'),
    ('Shorts', '1'),
    ('Skirts', '1'),
    ('Socks', '1'),
    ('Sports bras', '1'),
    ('Sweatshirts', '1'),
    ('Tops', '1'),
    ('Only include styles that can be worn with a standard bra', '2'),
    ('Include styles that are halter-bra friendly', '2'),
    ('Include styles that are cross-back-bra or racerback-bra friendly', '2'),
    ('Include styles that are strapless-bra friendly', '2'),
    ('Include styles that are not bra friendly', '2'),
    ('Cape', '3'),
    ('Cropped', '3'),
    ('Moto', '3'),
    ('Open front', '3'),
    ('Overcoat', '3'),
    ('Parka', '3'),
    ('Peacoat', '3'),
    ('Poncho', '3'),
    ('Puffer', '3'),
    ('Quilted', '3'),
    ('Raincoat', '3'),
    ('Trenchcoat', '3'),
    ('Windbreaker', '3'),
    ('Wrap', '3'),
    ('Coated', '5'),
    ('Exposed buttons', '5'),
    ('Printed', '5'),
    ('Raw hem', '5'),
    ('Ripped', '5'),
    ('Black', '5'),
    ('Blue', '5'),
    ('Color', '5'),
    ('Grey', '5'),
    ('White', '5'),
    ('Short', '6'),
    ('Knee length', '6'),
    ('Below the knee', '6'),
    ('Long', '6'),
    ('Bodycon', '7'),
    ('Drop waist', '7'),
    ('Empire waist', '7'),
    ('Peplum', '7'),
    ('Puff sleeve', '7'),
    ('Shirtdress', '7'),
    ('Slipdress', '7'),
    ('Sweater dress', '7'),
    ('T-shirt dress', '7'),
    ('Swing dress', '7'),
    ('Wrap dress', '7'),
    ('Contoured', '8'),
    ('Pleated', '8'),
    ('Fedora', '9'),
    ('Hair bands', '9'),
    ('Head wraps', '9'),
    ('Straw hat', '9'),
    ('26" or shorter', '10'),
    ('27" to 29"', '10'),
    ('30" to 31"', '10'),
    ('32" or longer', '10'),
    ('Bodysuits', '11'),
    ('Bras', '11'),
    ('Camisoles', '11'),
    ('Chemises', '11'),
    ('Panties', '11'),
    ('Boat neck', '12'),
    ('Collared', '12'),
    ('Crewneck', '12'),
    ('Halterneck', '12'),
    ('Low-cut necline', '12'),
    ('Mock turtleneck', '12'),
    ('Off the shoulder', '12'),
    ('One shoulder', '12'),
    ('Plunging 12', '12'),
    ('Shawl collar', '12'),
    ('Square 12', '12'),
    ('Strapless', '12'),
    ('Sweetheart 12', '12'),
    ('Turtleneck', '12'),
    ('V-neck', '12'),
    ('Zip', '12'),
    ('Office friendly', '13'),
    ('High rise', '14'),
    ('Mid rise', '14'),
    ('Low rise', '14'),
    ('Bootcut', '15'),
    ('Boyfriend', '15'),
    ('Side zip', '15'),
    ('Skinny', '15'),
    ('Slim bootcut', '15'),
    ('Straight', '15'),
    ('Tapered', '15'),
    ('Wide leg', '15'),
    ('Has pockets', '16'),
    ('A-line', '18'),
    ('Active', '18'),
    ('Bodycon', '18'),
    ('Circle', '18'),
    ('Cover-up', '18'),
    ('Pencil', '18'),
    ('Pleated', '18'),
    ('Slip', '18'),
    ('Tulip', '18'),
    ('Wrap', '18'),
    ('No-show', '20'),
    ('Ankle', '20'),
    ('Mid-calf', '20'),
    ('Knee high', '20'),
    ('Over-the-knee', '20'),
    ('Tights', '20'),
    ('Strapless', '19'),
    ('Sleeveless', '19'),
    ('Cap sleeve', '19'),
    ('Short sleeve', '19'),
    ('3/4 sleeve', '19'),
    ('Long sleeve', '19'),
    ('Bikinis and tankinis', '21'),
    ('One-pieces', '21'),
    ('Amour Vert', '22'),
    ('Sézane', '22'),
    ('Organic', '23'),
    ('GOTS', '23'),
    ('OEKO-TEX', '23'),
    ('Black', '24'),
    ('Grey', '24'),
    ('White', '24'),
    ('Off-white', '24'),
    ('Beige', '24'),
    ('Brown', '24'),
    ('Purple', '24'),
    ('Blue', '24'),
    ('Green', '24'),
    ('Yellow', '24'),
    ('Orange', '24'),
    ('Pink', '24'),
    ('Red', '24'),
    ('Pastel colors', '24'),
    ('Bright colors', '24'),
    ('Dark colors', '24'),
    ('Jersey', '25'),
    ('Jacquard', '25'),
    ('Faux leather', '25'),
    ('Poplin', '25'),
    ('Knit', '25'),
    ('Woven', '25'),
    ('Cotton', '26'),
    ('Alpaca', '26'),
    ('Spandex', '26'),
    ('Dry clean', '27'),
    ('Machine wash', '27'),
    ('Undisclosed', '27'),
    ('Dry flat', '28'),
    ('Hang to dry', '28'),
    ('Tumble dry low', '28'),
    ('Undisclosed', '28'),
    ('Under $25', '29'),
    ('$25 - $50', '29'),
    ('$50 - $100', '29'),
    ('$100 - $150', '29'),
    ('$150 - $200', '29'),
    ('$200 - $300', '29'),
    ('$300 - $500', '29'),
    ('$500 - $1,000', '29'),
    ('Over $1,000', '29'),
    ('Standard', '30'),
    ('Petite', '30'),
    ('Tall', '30'),
    ('Maternity', '30'),
    ('Tall plus', '30'),
    ('Plus maternity', '30'),
    ('0, XS', '31'),
    ('2, XS', '31'),
    ('4, S', '31'),
    ('6, S', '31'),
    ('8, M', '31'),
    ('10, M', '31'),
    ('12, L', '31'),
    ('14, L', '31'),
    ('16, XL', '31'),
    ('18, XL', '31'),
    ('20, 2X', '31'),
    ('22, 3X', '31'),
    ('24, 3X', '31'),
    ('26, 4X', '31'),
    ('28, 4X', '31');