-- insert into categories
-- (english_name, class)
-- values
--     ('Activewear', 'clothing'),
--     ('Blazers', 'clothing'),
--     ('Coats and Jackets', 'clothing'),
--     ('Dresses', 'clothing'),
--     ('Facemasks', 'accessories'),
--     ('Hair Accessories and Hats', 'accessories'),
--     ('Jeans', 'clothing'),
--     ('Jumpsuits', 'clothing'),
--     ('Lingerie, Shapewear, and Loungewear', 'clothing'),
--     ('Pants', 'clothing'),
--     ('Shoes', 'shoes'),
--     ('Skirts', 'clothing'),
--     ('Socks and Tights', 'clothing'),
--     ('Sweaters', 'clothing'),
--     ('Swimwear', 'clothing'),
--     ('Tops', 'clothing');